spring:
    profiles:
        active: local

---

spring:
    config:
        activate:
            on-profile: local
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher

server:
    port: 9000